import type { NextPage } from "next"
import Head from "next/head"

import { HeaderSection } from "../components/header-section"

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Pokemon Market</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container px-4 py-2 sm:px-auto mx-auto w-full divide-y divide-white-darker ">
        <HeaderSection />

        <main>Choose card</main>
      </div>
    </>
  )
}

export default Home
