import Head from "next/head"

import { Filter, FilterDropdownPosition } from "../components/filter"
import { HeaderSection } from "../components/header-section"
import { PokemonCard } from "../components/pokemon-card"
import { Pagination } from "../components/pagination"
import { useCardPagination } from "../utils/usePagination"
import { ShoppingCartOverlay } from "../components/shopping-cart-overlay"

const Home = () => {
  const {
    cards,
    pageIndex,
    setPageIndex,
    pageCount,
    filter: { sets, types, rarities, setFilter },
  } = useCardPagination()

  return (
    <div className="relative">
      <Head>
        <title>Pokemon Market</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container px-4 py-2 sm:px-auto mx-auto w-full divide-y divide-white-darker">
        <HeaderSection />

        <main>
          <div className="flex flex-wrap justify-between items-center">
            <h1 className="text-xl my-8 w-full md:w-auto">Choose card</h1>
            <div className="flex gap-2">
              {sets && (
                <Filter
                  name="Set"
                  data={sets.data.map(set => set.name).sort()}
                  onUpdateFilter={value =>
                    setFilter(prev => ({ ...prev, set: value }))
                  }
                />
              )}
              {rarities && (
                <Filter
                  name="Rarity"
                  data={rarities.data}
                  onUpdateFilter={value =>
                    setFilter(prev => ({ ...prev, rarity: value }))
                  }
                />
              )}
              {types && (
                <Filter
                  name="Type"
                  data={types.data}
                  position={FilterDropdownPosition.Right}
                  onUpdateFilter={value =>
                    setFilter(prev => ({ ...prev, type: value }))
                  }
                />
              )}
            </div>
          </div>

          <Pagination
            pageCount={pageCount}
            pageIndex={pageIndex}
            setPage={setPageIndex}
          />

          {cards ? (
            <div className="grid gap-4 grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5 2xl:grid-cols-6">
              {cards.data.map(card => (
                <PokemonCard key={card.id} card={card} />
              ))}
            </div>
          ) : (
            <div className="py-5 mx-auto container">...Loading</div>
          )}

          <Pagination
            pageCount={pageCount}
            pageIndex={pageIndex}
            setPage={setPageIndex}
          />
        </main>
      </div>

      <ShoppingCartOverlay />
    </div>
  )
}

export default Home
